### ISSUE TITLE
Teleporters

### ISSUE THREAD

**Issue by xXumarkuXx** [TheApocalypseMC/Issues#2]
### What is the problem?
Teleporters dose not teleport the player after selecting the location on the GUI

### What plugin are you experiencing the problem with?
Slimefun 4

### What steps can be taken to reproduce the problem?
1. Make the Teleporter
2. Setup teleport locations with gps
3. Step on the teleporter pressure plate
4. Click on a location from the opened GUI
5. Issue here (Dont start the teleportation process)

### Is there any extra information you want us to know? (Screenshots, additional error messages, etc.)
Console Error:
`08/18/2016 20:40:16
20:40:16 at me.mrCookieSlime.CSCoreLibPlugin.general.World.TitleBuilder.send(TitleBuilder.java:58)
at me.mrCookieSlime.Slimefun.GPS.TeleportationSequence.updateProgress(TeleportationSequence.java:92)
at me.mrCookieSlime.Slimefun.GPS.TeleportationSequence.start(TeleportationSequence.java:26)
at me.mrCookieSlime.Slimefun.GPS.GPSNetwork$16.onClick(GPSNetwork.java:365)
at me.mrCookieSlime.CSCoreLibPlugin.events.Listeners.MenuClickListener.onClick(MenuClickListener.java:33)
at sun.reflect.GeneratedMethodAccessor509.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.massivecraft.massivelag.inject.event.MassiveLagEventExecutor.execute(MassiveLagEventExecutor.java:67)
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1899)
at net.minecraft.server.v1_9_R2.PacketPlayInWindowClick.a(SourceFile:33)
at net.minecraft.server.v1_9_R2.PacketPlayInWindowClick.a(SourceFile:10)
at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45)
at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:786)
at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:403)
at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:723)
at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:622)
at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 3
at com.google.gson.internal.Streams.parse(Streams.java:56)
at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:54)
at net.minecraft.server.v1_9_R2.ChatDeserializer.a(SourceFile:501)
at net.minecraft.server.v1_9_R2.ChatDeserializer.a(SourceFile:512)
at net.minecraft.server.v1_9_R2.IChatBaseComponent$ChatSerializer.a(SourceFile:205)
... 29 more
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 3
at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505)
at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1386)
at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:497)
at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:403)
at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:666)
at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:642)
at com.google.gson.internal.Streams.parse(Streams.java:44)
... 33 more`

**Comment by xXumarkuXx** [comment]
Fixed
